-- =====================================
-- schema2.sql (revisado)
-- Fluxo de pedidos
-- Depende de: Produtos, Itens, OMs
-- =====================================

BEGIN;

-- 1) Pedidos (cabeçalho)
CREATE TABLE IF NOT EXISTS pedidos (
    id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    om_id         INT NOT NULL REFERENCES oms(id) ON DELETE RESTRICT,
    status        VARCHAR(15) NOT NULL,
    data_pedido   TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_entrega  TIMESTAMPTZ NULL,
    observacoes   TEXT,
    cadastrado_por VARCHAR(80) NOT NULL DEFAULT 'Sub Ten Gutierres',

    CONSTRAINT chk_pedidos_status CHECK (status IN ('aberto','entregue','cancelado')),
    -- Coerência entre status e data_entrega
    CONSTRAINT chk_pedidos_entrega_coerente CHECK (
        (status = 'entregue' AND data_entrega IS NOT NULL) OR
        (status IN ('aberto','cancelado') AND data_entrega IS NULL)
    ),
    -- Entrega não pode ser antes do pedido
    CONSTRAINT chk_pedidos_entrega_posterior CHECK (
        data_entrega IS NULL OR data_entrega >= data_pedido
    )
);

-- Índices úteis
CREATE INDEX IF NOT EXISTS idx_pedidos_status_data ON pedidos (status, data_pedido DESC);
CREATE INDEX IF NOT EXISTS idx_pedidos_om ON pedidos (om_id);

-- Auto-ajuste de data_entrega conforme status
CREATE OR REPLACE FUNCTION fn_pedidos_autoset_data_entrega()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
BEGIN
    IF NEW.status = 'entregue' AND NEW.data_entrega IS NULL THEN
        NEW.data_entrega := CURRENT_TIMESTAMP;
    ELSIF NEW.status IN ('aberto','cancelado') THEN
        NEW.data_entrega := NULL;
    END IF;
    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedidos_autoset_data_entrega ON pedidos;
CREATE TRIGGER trg_pedidos_autoset_data_entrega
BEFORE INSERT OR UPDATE ON pedidos
FOR EACH ROW
EXECUTE FUNCTION fn_pedidos_autoset_data_entrega();

-- Não permitir marcar como 'entregue' com pendências
CREATE OR REPLACE FUNCTION fn_pedidos_bloqueia_entrega_com_pendencia()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  total_solicitado INT;
  total_atendido   INT;
BEGIN
  IF NEW.status = 'entregue' THEN
    SELECT COALESCE(SUM(quantidade_solicitada),0),
           COALESCE(SUM(quantidade_atendida),0)
      INTO total_solicitado, total_atendido
      FROM pedido_itens
     WHERE pedido_id = NEW.id;

    -- opcional: exigir que exista pelo menos 1 item no pedido
    IF total_solicitado = 0 THEN
      RAISE EXCEPTION 'Pedido % não pode ser entregue sem itens.', NEW.id;
    END IF;

    IF total_atendido < total_solicitado THEN
      RAISE EXCEPTION 'Pedido % não pode ser entregue: pendência de % itens.',
        NEW.id, (total_solicitado - total_atendido);
    END IF;
  END IF;

  -- Se marcar como cancelado, impedir cancelamento com atendimento já efetuado (regra conservadora)
  IF NEW.status = 'cancelado' THEN
    SELECT COALESCE(SUM(quantidade_atendida),0) INTO total_atendido
      FROM pedido_itens WHERE pedido_id = NEW.id;
    IF total_atendido > 0 THEN
      RAISE EXCEPTION 'Pedido % não pode ser cancelado: já há atendimento realizado (% itens).',
        NEW.id, total_atendido;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedidos_bloqueia_entrega_com_pendencia ON pedidos;
CREATE TRIGGER trg_pedidos_bloqueia_entrega_com_pendencia
BEFORE UPDATE ON pedidos
FOR EACH ROW
EXECUTE FUNCTION fn_pedidos_bloqueia_entrega_com_pendencia();

-- 2) Itens do Pedido (linhas)
CREATE TABLE IF NOT EXISTS pedido_itens (
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_id              INT NOT NULL REFERENCES pedidos(id) ON DELETE CASCADE,
    codigo_produto         INT NOT NULL REFERENCES produtos(codigo) ON DELETE RESTRICT,
    quantidade_solicitada  INT NOT NULL CHECK (quantidade_solicitada > 0),
    quantidade_atendida    INT NOT NULL DEFAULT 0 CHECK (quantidade_atendida >= 0),
    cadastrado_por         VARCHAR(80) NOT NULL DEFAULT 'Sub Ten Gutierres',
    CONSTRAINT uq_pedido_produto UNIQUE (pedido_id, codigo_produto)
);

CREATE INDEX IF NOT EXISTS idx_pedido_itens_pedido  ON pedido_itens (pedido_id);
CREATE INDEX IF NOT EXISTS idx_pedido_itens_produto ON pedido_itens (codigo_produto);

-- Não exceder solicitada; bloquear alterações se pedido estiver cancelado
CREATE OR REPLACE FUNCTION fn_pedido_itens_valida()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  v_status VARCHAR(15);
BEGIN
  SELECT status INTO v_status FROM pedidos WHERE id = NEW.pedido_id;

  IF v_status = 'cancelado' THEN
    RAISE EXCEPTION 'Pedido % cancelado: não é permitido alterar itens.', NEW.pedido_id;
  END IF;

  IF NEW.quantidade_atendida > NEW.quantidade_solicitada THEN
    RAISE EXCEPTION
      'quantidade_atendida (%) excede quantidade_solicitada (%) para (pedido_id=% , produto=%)',
      NEW.quantidade_atendida, NEW.quantidade_solicitada, NEW.pedido_id, NEW.codigo_produto;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedido_itens_valida ON pedido_itens;
CREATE TRIGGER trg_pedido_itens_valida
BEFORE INSERT OR UPDATE ON pedido_itens
FOR EACH ROW
EXECUTE FUNCTION fn_pedido_itens_valida();

-- (Opcional) Impedir excluir linhas se pedido estiver cancelado ou entregue
CREATE OR REPLACE FUNCTION fn_pedido_itens_bloqueia_delete()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  v_status VARCHAR(15);
BEGIN
  SELECT status INTO v_status FROM pedidos WHERE id = OLD.pedido_id;
  IF v_status IN ('entregue','cancelado') THEN
    RAISE EXCEPTION 'Pedido % (%): exclusão de itens não permitida.', OLD.pedido_id, v_status;
  END IF;
  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedido_itens_bloqueia_delete ON pedido_itens;
CREATE TRIGGER trg_pedido_itens_bloqueia_delete
BEFORE DELETE ON pedido_itens
FOR EACH ROW
EXECUTE FUNCTION fn_pedido_itens_bloqueia_delete();

-- 7) Views de apoio

-- Pedidos abertos com totais e % atendimento
CREATE OR REPLACE VIEW vw_pedidos_abertos AS
SELECT
    p.id, p.om_id, p.status, p.data_pedido,
    COALESCE(SUM(pi.quantidade_solicitada),0) AS total_solicitado,
    COALESCE(SUM(pi.quantidade_atendida),0)   AS total_atendido,
    CASE
      WHEN SUM(pi.quantidade_solicitada) IS NULL OR SUM(pi.quantidade_solicitada) = 0
        THEN 100
      ELSE ROUND(100.0 * COALESCE(SUM(pi.quantidade_atendida),0) / NULLIF(SUM(pi.quantidade_solicitada),0), 2)
    END AS percentual_atendimento
FROM pedidos p
LEFT JOIN pedido_itens pi ON pi.pedido_id = p.id
WHERE p.status = 'aberto'
GROUP BY p.id, p.om_id, p.status, p.data_pedido
ORDER BY p.data_pedido DESC;

-- Linhas com pendência (backorder) para pedidos abertos
CREATE OR REPLACE VIEW vw_backorder AS
SELECT
    pi.id AS pedido_item_id,
    pi.pedido_id,
    pi.codigo_produto,
    pi.quantidade_solicitada,
    pi.quantidade_atendida,
    (pi.quantidade_solicitada - pi.quantidade_atendida) AS pendente
FROM pedido_itens pi
JOIN pedidos p ON p.id = pi.pedido_id
WHERE (pi.quantidade_solicitada - pi.quantidade_atendida) > 0
  AND p.status = 'aberto'
ORDER BY pi.pedido_id, pi.codigo_produto;

CREATE OR REPLACE VIEW vw_pedidos_overview AS
SELECT
  p.id,
  o.sigla            AS om_sigla,
  p.data_pedido,
  p.status,
  p.observacoes,
  COALESCE(SUM(pi.quantidade_solicitada), 0) AS total_solicitada,
  COALESCE(SUM(pi.quantidade_atendida),  0) AS total_atendida,
  CASE
    WHEN NULLIF(SUM(pi.quantidade_solicitada),0) IS NULL THEN 100.0
    ELSE ROUND(100.0 * SUM(pi.quantidade_atendida)::numeric / NULLIF(SUM(pi.quantidade_solicitada),0), 2)
  END AS percentual_entregue
FROM pedidos p
JOIN oms o                ON o.id = p.om_id
LEFT JOIN pedido_itens pi ON pi.pedido_id = p.id
GROUP BY p.id, o.sigla, p.data_pedido, p.status, p.observacoes
ORDER BY p.data_pedido DESC;


COMMIT;

