-- =====================================
-- schema1.sql (ajustado)
-- Base de Produtos, Itens e OMs.
-- =====================================

BEGIN;

-- Tabela: produtos
CREATE TABLE IF NOT EXISTS produtos (
    codigo      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao   VARCHAR(100) NOT NULL,
    categoria   VARCHAR(50)  NOT NULL,
    marca       VARCHAR(50)  NOT NULL
    -- Opcional: evitar duplicidade lógica
    -- , CONSTRAINT uq_produtos_desc_cat_marca UNIQUE (descricao, categoria, marca)
);

-- Tabela: itens (unidades físicas com RFID)
CREATE TABLE IF NOT EXISTS itens (
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_produto              INT NOT NULL,
    etiqueta_rfid               VARCHAR(50) UNIQUE NOT NULL,
    timestamp_entrada           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_validade               DATE,
    timestamp_saida             TIMESTAMPTZ, -- NULL => ainda em estoque
    ultima_verificacao          TIMESTAMPTZ, -- última leitura do leitor RFID (heartbeat do item)
    origem_ultima_verificacao   VARCHAR(50), -- opcional: ID do leitor/antena/região
    cadastrado_por              VARCHAR(80) NOT NULL DEFAULT 'Sub Ten Gutierres',

    CONSTRAINT fk_itens_produtos
        FOREIGN KEY (codigo_produto)
        REFERENCES produtos (codigo)
        ON DELETE CASCADE,

    -- Coerência temporal mínima
    CONSTRAINT chk_itens_coerencia_temporal
        CHECK (
            (timestamp_saida IS NULL OR timestamp_saida >= timestamp_entrada)
            AND (ultima_verificacao IS NULL OR ultima_verificacao >= timestamp_entrada)
            AND (timestamp_saida IS NULL OR ultima_verificacao IS NULL OR ultima_verificacao <= timestamp_saida)
        ),

    -- RFID não pode ser string vazia/brancos
    CONSTRAINT chk_rfid_not_blank
        CHECK (btrim(etiqueta_rfid) <> '')
);

-- Índices úteis
CREATE INDEX IF NOT EXISTS idx_itens_codigo_produto ON itens (codigo_produto);

-- Parcial: acelera contagem de itens em estoque
CREATE INDEX IF NOT EXISTS idx_itens_em_estoque ON itens (codigo_produto) WHERE timestamp_saida IS NULL;

-- (REMOVIDO) Índice redundante em etiqueta_rfid - já existe pelo UNIQUE
-- CREATE INDEX IF NOT EXISTS idx_itens_rfid ON itens (etiqueta_rfid);

-- VIEW: produtos com quantidades derivadas
CREATE OR REPLACE VIEW vw_produtos_quantidade AS
SELECT
    p.codigo,
    p.descricao,
    p.categoria,
    p.marca,
    COUNT(i.id) FILTER (WHERE i.timestamp_saida IS NULL) AS quantidade_em_estoque,
    COUNT(i.id) AS quantidade_total
FROM produtos p
LEFT JOIN itens i ON i.codigo_produto = p.codigo
GROUP BY p.codigo, p.descricao, p.categoria, p.marca;

-- 1) OM (Organização Solicitante)
CREATE TABLE IF NOT EXISTS oms (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla   VARCHAR(30)  NOT NULL UNIQUE,
    nome    VARCHAR(120) NOT NULL
);

COMMIT;

-- =====================================
-- USUÁRIOS (login/cadastro com senha hash)
-- Acrescente ao final do schema1.sql
-- =====================================
BEGIN;

-- Case-insensitive text (garante UNIQUE ignorando maiúsculas/minúsculas)
CREATE EXTENSION IF NOT EXISTS citext;

-- Usuários do sistema
CREATE TABLE IF NOT EXISTS users (
    id               BIGSERIAL PRIMARY KEY,
    -- "Nome de Guerra" do formulário
    username         CITEXT      NOT NULL UNIQUE,
    -- E-mail com UNIQUE case-insensitive
    email            CITEXT      NOT NULL UNIQUE,
    -- Posto/Graduação (por enquanto livre; depois podemos trocar por FK de uma tabela de domínio)
    posto_graduacao  VARCHAR(40) NOT NULL,
    -- SEMPRE hash, nunca senha em claro
    password_hash    TEXT        NOT NULL,

    -- Opcional: associação a uma OM (se fizer sentido no seu fluxo)
    om_id            INT REFERENCES oms(id) ON DELETE SET NULL,

    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),

    -- Regras de sanidade
    CONSTRAINT chk_username_not_blank   CHECK (btrim(username::text) <> ''),
    CONSTRAINT chk_email_format         CHECK (email ~* '^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$'),
    -- Hash costuma ser bem maior; evita strings vazias/curtas por engano
    CONSTRAINT chk_passwordhash_length  CHECK (length(password_hash) >= 20)
);

-- Índice útil para consultas por OM
CREATE INDEX IF NOT EXISTS idx_users_om ON users(om_id);

-- Trigger para updated_at automático
CREATE OR REPLACE FUNCTION trg_set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'set_users_updated_at'
  ) THEN
    CREATE TRIGGER set_users_updated_at
    BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
  END IF;
END$$;


-- Refresh tokens persistidos (revogação por JTI)
CREATE TABLE IF NOT EXISTS refresh_tokens (
  id           BIGSERIAL PRIMARY KEY,
  user_id      BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_jti    TEXT   NOT NULL UNIQUE,
  expires_at   TIMESTAMPTZ NOT NULL,
  revoked_at   TIMESTAMPTZ NULL,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_refresh_user ON refresh_tokens(user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_valid ON refresh_tokens(expires_at) WHERE revoked_at IS NULL;


COMMIT;


BEGIN;

-- Adiciona coluna is_admin à tabela users
ALTER TABLE users 
ADD COLUMN IF NOT EXISTS is_admin BOOLEAN NOT NULL DEFAULT FALSE;

-- Índice para consultas de usuários admin
CREATE INDEX IF NOT EXISTS idx_users_is_admin ON users(is_admin) WHERE is_admin = TRUE;

-- Comentário descritivo
COMMENT ON COLUMN users.is_admin IS 'Indica se o usuário possui privilégios de administrador';

COMMIT;





