-- =====================================
-- schema3.sql 
-- Vinculação de itens RFID aos pedidos, histórico e regras de cancelamento
-- Depende de: produtos, itens, oms, pedidos, pedido_itens
-- =====================================

BEGIN;

-- 1) Tabela de vínculos: qual ITEM (RFID) atende qual linha do pedido
CREATE TABLE IF NOT EXISTS pedido_item_vinculos (
    id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pedido_item_id     INT NOT NULL REFERENCES pedido_itens(id) ON DELETE CASCADE,
    item_id            INT NOT NULL REFERENCES itens(id) ON DELETE RESTRICT,
    origem_vinculo     VARCHAR(50),  -- e.g., leitor/antena/região
    vinculado_por      VARCHAR(80) NOT NULL DEFAULT 'Sub Ten Gutierres',
    vinculado_em       TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    -- Um item só pode ser vinculado uma única vez (a um único pedido/linha)
    CONSTRAINT uq_vinculo_item UNIQUE (item_id),

    -- Não vincular o mesmo item duas vezes à mesma linha
    CONSTRAINT uq_vinculo_pedido_item UNIQUE (pedido_item_id, item_id)
);

CREATE INDEX IF NOT EXISTS idx_vinculos_pedido_item ON pedido_item_vinculos (pedido_item_id);
CREATE INDEX IF NOT EXISTS idx_vinculos_item ON pedido_item_vinculos (item_id);

-- 2) Função de validação e efeitos colaterais no vínculo
--    - Checa status do pedido (não pode estar cancelado)
--    - Garante correspondência de produto (item.codigo_produto == pedido_itens.codigo_produto)
--    - Garante que o item está em estoque (timestamp_saida IS NULL)
--    - Garante que ainda há saldo a atender (vínculos < quantidade_solicitada)
--    - Marca a saída do item e atualiza quantidade_atendida (+1)
CREATE OR REPLACE FUNCTION fn_vinculo_valida_e_aplica()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  v_status               VARCHAR(15);
  v_pedido_id            INT;
  v_codigo_produto_linha INT;
  v_codigo_produto_item  INT;
  v_solicitada           INT;
  v_atual_vinculos       INT;
BEGIN
  -- Obter cabeçalho do pedido e dados da linha
  SELECT pi.pedido_id, pi.codigo_produto, pi.quantidade_solicitada
    INTO v_pedido_id, v_codigo_produto_linha, v_solicitada
    FROM pedido_itens pi
   WHERE pi.id = NEW.pedido_item_id;

  IF v_pedido_id IS NULL THEN
    RAISE EXCEPTION 'Linha de pedido % não existe.', NEW.pedido_item_id;
  END IF;

  SELECT status INTO v_status FROM pedidos WHERE id = v_pedido_id;

  IF v_status = 'cancelado' THEN
    RAISE EXCEPTION 'Pedido % está cancelado: não é permitido vincular itens.', v_pedido_id;
  END IF;

  -- Verificar produto do item
  SELECT codigo_produto INTO v_codigo_produto_item FROM itens WHERE id = NEW.item_id;

  IF v_codigo_produto_item IS NULL THEN
    RAISE EXCEPTION 'Item % inexistente.', NEW.item_id;
  END IF;

  IF v_codigo_produto_item <> v_codigo_produto_linha THEN
    RAISE EXCEPTION 'Item % (produto=%) não corresponde à linha (produto=%).',
      NEW.item_id, v_codigo_produto_item, v_codigo_produto_linha;
  END IF;

  -- Item precisa estar em estoque (sem saída registrada)
  PERFORM 1 FROM itens WHERE id = NEW.item_id AND timestamp_saida IS NULL;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Item % já está fora de estoque; não pode ser vinculado.', NEW.item_id;
  END IF;

  -- Checar saldo da linha (não exceder solicitada)
  SELECT COUNT(*) INTO v_atual_vinculos
    FROM pedido_item_vinculos
   WHERE pedido_item_id = NEW.pedido_item_id;

  IF v_atual_vinculos >= v_solicitada THEN
    RAISE EXCEPTION 'Linha % já atingiu a quantidade solicitada (%).',
      NEW.pedido_item_id, v_solicitada;
  END IF;

  -- Marcar saída do item no ato do vínculo (baixa de estoque)
  UPDATE itens
     SET timestamp_saida = COALESCE(timestamp_saida, CURRENT_TIMESTAMP),
         ultima_verificacao = CURRENT_TIMESTAMP,
         origem_ultima_verificacao = COALESCE(NEW.origem_vinculo, origem_ultima_verificacao)
   WHERE id = NEW.item_id;

  -- Atualizar quantidade_atendida da linha para o novo total (vínculos existentes + este)
  UPDATE pedido_itens
     SET quantidade_atendida = v_atual_vinculos + 1
   WHERE id = NEW.pedido_item_id;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_vinculo_valida_e_aplica ON pedido_item_vinculos;
CREATE TRIGGER trg_vinculo_valida_e_aplica
BEFORE INSERT ON pedido_item_vinculos
FOR EACH ROW
EXECUTE FUNCTION fn_vinculo_valida_e_aplica();

-- 3) Após inserir um vínculo, avaliar se o pedido ficou completamente atendido;
--    se sim, marcar status = 'entregue' (o trigger do pedido ajusta data_entrega)
CREATE OR REPLACE FUNCTION fn_vinculo_autoentrega_pedido()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  v_pedido_id INT;
  v_total_solicitado INT;
  v_total_atendido   INT;
BEGIN
  SELECT pedido_id INTO v_pedido_id FROM pedido_itens WHERE id = NEW.pedido_item_id;

  SELECT COALESCE(SUM(quantidade_solicitada),0),
         COALESCE(SUM(quantidade_atendida),0)
    INTO v_total_solicitado, v_total_atendido
    FROM pedido_itens
   WHERE pedido_id = v_pedido_id;

  IF v_total_solicitado > 0 AND v_total_atendido = v_total_solicitado THEN
    UPDATE pedidos
       SET status = 'entregue'
     WHERE id = v_pedido_id
       AND status <> 'entregue';
    -- (triggers existentes em "pedidos" já ajustam data_entrega e validam coerência)
  END IF;

  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_vinculo_autoentrega_pedido ON pedido_item_vinculos;
CREATE TRIGGER trg_vinculo_autoentrega_pedido
AFTER INSERT ON pedido_item_vinculos
FOR EACH ROW
EXECUTE FUNCTION fn_vinculo_autoentrega_pedido();

-- 4) Se um vínculo for removido, re-sincronizar quantidade_atendida e,
--    se necessário, reabrir o pedido para 'aberto'.
CREATE OR REPLACE FUNCTION fn_vinculo_sync_delete()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  v_pedido_id INT;
  v_total_solicitado INT;
  v_total_atendido   INT;
BEGIN
  -- Recalcular atendida da linha
  UPDATE pedido_itens
     SET quantidade_atendida = (
       SELECT COUNT(*) FROM pedido_item_vinculos WHERE pedido_item_id = OLD.pedido_item_id
     )
   WHERE id = OLD.pedido_item_id;

  -- Verificar status do pedido
  SELECT pedido_id INTO v_pedido_id FROM pedido_itens WHERE id = OLD.pedido_item_id;

  SELECT COALESCE(SUM(quantidade_solicitada),0),
         COALESCE(SUM(quantidade_atendida),0)
    INTO v_total_solicitado, v_total_atendido
    FROM pedido_itens
   WHERE pedido_id = v_pedido_id;

  -- Se ficou com pendência, reabrir (caso estivesse 'entregue')
  IF v_total_atendido < v_total_solicitado THEN
    UPDATE pedidos SET status = 'aberto' WHERE id = v_pedido_id AND status = 'entregue';
    UPDATE pedidos SET data_entrega = NULL WHERE id = v_pedido_id AND status = 'aberto';
  END IF;

  RETURN OLD;
END;
$$;

DROP TRIGGER IF EXISTS trg_vinculo_sync_delete ON pedido_item_vinculos;
CREATE TRIGGER trg_vinculo_sync_delete
AFTER DELETE ON pedido_item_vinculos
FOR EACH ROW
EXECUTE FUNCTION fn_vinculo_sync_delete();

-- 5) Cancelamento: limpar automaticamente as linhas do pedido (e os vínculos via CASCADE)
--    (schema2 já bloqueia cancelar com atendimento>0; reforçamos a checagem)
CREATE OR REPLACE FUNCTION fn_pedidos_limpa_itens_ao_cancelar()
RETURNS TRIGGER
LANGUAGE plpgsql AS $$
DECLARE
  v_atendido INT;
BEGIN
  IF NEW.status = 'cancelado' AND OLD.status <> 'cancelado' THEN
    -- Segurança extra: não permitir cancelar parcialmente atendido
    SELECT COALESCE(SUM(quantidade_atendida),0) INTO v_atendido
      FROM pedido_itens WHERE pedido_id = NEW.id;

    IF v_atendido > 0 THEN
      RAISE EXCEPTION 'Pedido % não pode ser cancelado: já possui atendimento (% itens).', NEW.id, v_atendido;
    END IF;

    -- Limpar linhas ANTES de virar cancelado (evita bloqueio do BEFORE DELETE de pedido_itens)
    DELETE FROM pedido_itens WHERE pedido_id = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pedidos_limpa_itens_ao_cancelar ON pedidos;
CREATE TRIGGER trg_pedidos_limpa_itens_ao_cancelar
BEFORE UPDATE OF status ON pedidos
FOR EACH ROW
EXECUTE FUNCTION fn_pedidos_limpa_itens_ao_cancelar();

-- 6) View de histórico de pedidos entregues com itens e responsáveis
CREATE OR REPLACE VIEW vw_pedidos_entregues_detalhe AS
SELECT
  p.id                         AS pedido_id,
  p.data_pedido,
  p.data_entrega,
  om.sigla                     AS om_sigla,
  om.nome                      AS om_nome,
  pi.codigo_produto,
  pr.descricao                 AS produto_descricao,
  pr.categoria                 AS produto_categoria,
  pr.marca                     AS produto_marca,
  v.item_id,
  it.etiqueta_rfid,
  v.vinculado_por,
  v.vinculado_em,
  v.origem_vinculo
FROM pedidos p
JOIN oms om                       ON om.id = p.om_id
JOIN pedido_itens pi              ON pi.pedido_id = p.id
JOIN produtos pr                  ON pr.codigo = pi.codigo_produto
LEFT JOIN pedido_item_vinculos v  ON v.pedido_item_id = pi.id
LEFT JOIN itens it                ON it.id = v.item_id
WHERE p.status = 'entregue'
ORDER BY p.data_entrega DESC, p.id, pi.codigo_produto, v.vinculado_em;

-- 7) (Opcional) Função utilitária para UX/API:
--    Vincular por pedido, produto e RFID (resolve IDs e insere vínculo)
CREATE OR REPLACE FUNCTION sp_vincular_item_por_rfid(
  p_pedido_id INT,
  p_codigo_produto INT,
  p_etiqueta_rfid VARCHAR,
  p_vinculado_por VARCHAR DEFAULT 'Sub Ten Gutierres',
  p_origem VARCHAR DEFAULT NULL
) RETURNS VOID
LANGUAGE plpgsql AS $$
DECLARE
  v_pedido_item_id INT;
  v_item_id INT;
BEGIN
  SELECT id INTO v_pedido_item_id
    FROM pedido_itens
   WHERE pedido_id = p_pedido_id
     AND codigo_produto = p_codigo_produto;

  IF v_pedido_item_id IS NULL THEN
    RAISE EXCEPTION 'Pedido % não possui linha para produto %.', p_pedido_id, p_codigo_produto;
  END IF;

  SELECT id INTO v_item_id FROM itens
   WHERE etiqueta_rfid = p_etiqueta_rfid;

  IF v_item_id IS NULL THEN
    RAISE EXCEPTION 'Item com RFID % não encontrado.', p_etiqueta_rfid;
  END IF;

  INSERT INTO pedido_item_vinculos (pedido_item_id, item_id, origem_vinculo, vinculado_por)
  VALUES (v_pedido_item_id, v_item_id, p_origem, p_vinculado_por);
END;
$$;

COMMIT;


