-- =====================================
-- schema1.sql (ajustado)
-- Base de Produtos, Itens e OMs.
-- =====================================

BEGIN;

-- Tabela: produtos
CREATE TABLE IF NOT EXISTS produtos (
    codigo      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao   VARCHAR(100) NOT NULL,
    categoria   VARCHAR(50)  NOT NULL,
    marca       VARCHAR(50)  NOT NULL
    -- Opcional: evitar duplicidade lógica
    -- , CONSTRAINT uq_produtos_desc_cat_marca UNIQUE (descricao, categoria, marca)
);

-- Tabela: itens (unidades físicas com RFID)
CREATE TABLE IF NOT EXISTS itens (
    id                          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_produto              INT NOT NULL,
    etiqueta_rfid               VARCHAR(50) UNIQUE NOT NULL,
    timestamp_entrada           TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_validade               DATE,
    timestamp_saida             TIMESTAMPTZ, -- NULL => ainda em estoque
    ultima_verificacao          TIMESTAMPTZ, -- última leitura do leitor RFID (heartbeat do item)
    origem_ultima_verificacao   VARCHAR(50), -- opcional: ID do leitor/antena/região
    cadastrado_por              VARCHAR(80) NOT NULL DEFAULT 'Sub Ten Gutierres',

    CONSTRAINT fk_itens_produtos
        FOREIGN KEY (codigo_produto)
        REFERENCES produtos (codigo)
        ON DELETE CASCADE,

    -- Coerência temporal mínima
    CONSTRAINT chk_itens_coerencia_temporal
        CHECK (
            (timestamp_saida IS NULL OR timestamp_saida >= timestamp_entrada)
            AND (ultima_verificacao IS NULL OR ultima_verificacao >= timestamp_entrada)
            AND (timestamp_saida IS NULL OR ultima_verificacao IS NULL OR ultima_verificacao <= timestamp_saida)
        ),

    -- RFID não pode ser string vazia/brancos
    CONSTRAINT chk_rfid_not_blank
        CHECK (btrim(etiqueta_rfid) <> '')
);

-- Índices úteis
CREATE INDEX IF NOT EXISTS idx_itens_codigo_produto ON itens (codigo_produto);

-- Parcial: acelera contagem de itens em estoque
CREATE INDEX IF NOT EXISTS idx_itens_em_estoque ON itens (codigo_produto) WHERE timestamp_saida IS NULL;

-- (REMOVIDO) Índice redundante em etiqueta_rfid - já existe pelo UNIQUE
-- CREATE INDEX IF NOT EXISTS idx_itens_rfid ON itens (etiqueta_rfid);

-- VIEW: produtos com quantidades derivadas
CREATE OR REPLACE VIEW vw_produtos_quantidade AS
SELECT
    p.codigo,
    p.descricao,
    p.categoria,
    p.marca,
    COUNT(i.id) FILTER (WHERE i.timestamp_saida IS NULL) AS quantidade_em_estoque,
    COUNT(i.id) AS quantidade_total
FROM produtos p
LEFT JOIN itens i ON i.codigo_produto = p.codigo
GROUP BY p.codigo, p.descricao, p.categoria, p.marca;

-- 1) OM (Organização Solicitante)
CREATE TABLE IF NOT EXISTS oms (
    id      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sigla   VARCHAR(30)  NOT NULL UNIQUE,
    nome    VARCHAR(120) NOT NULL
);

COMMIT;








